#matrix
version: '3.8'
services:
    synapse:
        image: matrixdotorg/synapse:v1.147.1
        container_name: synapse
        volumes:
            - data:/data
        ports:
            - "8008:8008"
        restart: unless-stopped
volumes:
    data:
